spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/cybersdb
    username: postgres
    password: YOUR_DATABASE_PASSWORD_HERE
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: YOUR_MAILTRAP_USERNAME_HERE
    password: YOUR_MAILTRAP_PASSWORD_HERE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

jwt:
  secret: "YOUR_JWT_SECRET_KEY_HERE"
  expiration-ms: 86400000  # 24 hours